version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm ci --omit=dev
  build:
    commands:
      - npm run build
  # post_build:
  #   commands:
  #     - npm run migrate
  #     - npm run start
artifacts:
  files:
    - '**/*'
  base-directory: '.'
