version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 16
  pre_build:
    commands:
      - npm ci --omit=dev
      - npm run keystone:postinstall
  build:
    commands:
      - npm run build
      - npm run prisma migrate
  # post_build:
  #   commands:
  #     - npm run migrate
  #     - npm run start
artifacts:
  files:
    - '**/*'
  base-directory: '.'
