version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm ci --omit=dev
      - npm run keystone:postinstall
  build:
    commands:
      - npm run build
      # - npx prisma db push # This step is needed at initial deploy
      - npm run prisma migrate # This step is needed after initial deploy (not needed at initial deploy)
  # post_build:
  #   commands:
  #     - npm run migrate
  #     - npm run start
artifacts:
  files:
    - '**/*'
  base-directory: '.'
