version: 0.2

# env:
#   variables:
#     NODE_ENV: production

phases:
  install:
    commands:
      - echo Entered the install phase...
      - npm ci --production --legacy-peer-deps
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
  migrate:
    commands:
      - echo Entered the migrate phase...
      - npm run migrate
  run:
    commands:
      - npm run start

# reports:
#   arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
#     files:
#       - "**/*"
#     base-directory: 'target/tests/reports'
#     discard-paths: no
#   reportGroupCucumberJson:
#     files:
#       - 'cucumber/target/cucumber-tests.xml'
#     discard-paths: yes
#     file-format: CUCUMBERJSON # default is JUNITXML
# artifacts:
#   files:
#     - target/messageUtil-1.0.jar
#   discard-paths: yes
#   secondary-artifacts:
#     artifact1:
#       files:
#         - target/artifact-1.0.jar
#       discard-paths: yes
#     artifact2:
#       files:
#         - target/artifact-2.0.jar
#       discard-paths: yes
# cache:
#   paths:
#     - '/root/.m2/**/*'
